### ISSUE TITLE
Crash on selecting store

### ISSUE THREAD

**Issue by itsforrest** [m1s3ry/minit-fun-racer-vita#1]
On game over, either "crash" or "out of time", if I select "STORE" in the menu the screen freezes. The music keeps playing though.

I have the Itch version of the game.

**Comment by m1s3ry** [comment]
Yeah, it won't work. It says in the install instructions

`IMPORTANT: This patch is not confirmed to work with any other version that it's not the current latest build of Steam (6471361). It should support other versions but it's very likely it won't properly.`

When I have a little money I'll make a patch for the itch version of the game
